### ISSUE TITLE
obsidian搜索遍历文件时能设置忽略 .obsidian 文件夹吗？

### ISSUE THREAD

**Issue by renmu123** [LanyuanXiaoyao-Studio/utools-recent-projects#1]
我是 ob 插件的开发者，我的插件文件夹中有很多 node_modules 的小文件，导致使用插件搜索时初始化很慢，希望能将这些文件忽略掉。

**Comment by lanyuanxiaoyao** [comment]
> 我是 ob 插件的开发者，我的插件文件夹中有很多 node_modules 的小文件，导致使用插件搜索时初始化很慢，希望能将这些文件忽略掉。

有点没明白你意思, 你说的「ob 插件」是指你自己开发的插件还是指用我的这个插件, 现在我这个插件里面确实没有做忽略文件夹的操作, 可以考虑增加.

如果你说的是你开发的插件的情况, 那你需要详细描述一下, 我没太懂你的意思

**Comment by lanyuanxiaoyao** [comment]
> 我是 ob 插件的开发者，我的插件文件夹中有很多 node_modules 的小文件，导致使用插件搜索时初始化很慢，希望能将这些文件忽略掉。

我看懂你的意思了, 你说的是 Obsidian 的插件开发, 下个版本把忽略 .obsidian 加上, 这两天吧

**Comment by renmu123** [comment]
感谢大佬

**Comment by lanyuanxiaoyao** [comment]
> 感谢大佬

插件市场已更新忽略 .obsidian 文件夹的版本
