### ISSUE TITLE
书签匹配逻辑

### ISSUE THREAD

**Issue by jing2si** [LanyuanXiaoyao-Studio/utools-recent-projects#2]
例如：我的书签标题是: **utools 快速启动 软件**

* 搜索 **utools 快速启动** 可以搜索到
* 搜索 **utools 软件** 搜索不到

* 搜索 **快速启动 软件** 可以搜索到
* 搜索 **软件 快速启动** 搜索不到

也是说必须保持文字顺序一致才能搜索，这样很不方便，因为书签多了，不可能按顺序记住的
原来用 Alfred 就可以，才开始试用的 HapiGo 也可以，谷歌浏览器自带的书签搜索就更强大了

> 这里我只是举例子哈，实际情况搜索 **utools** 就出来了， 我的书签有好几千个，每个标题里我都写的关键字，有点类似火狐的 tag，我想到啥，直接输入关键字就能出来，不用保持他的顺序

**Comment by lanyuanxiaoyao** [comment]
> 例如：我的书签标题是: **utools 快速启动 软件**
> 
> * 搜索 **utools 快速启动** 可以搜索到
> * 搜索 **utools 软件** 搜索不到
> 
> * 搜索 **快速启动 软件** 可以搜索到
> * 搜索 **软件 快速启动** 搜索不到
> 
> 也是说必须保持文字顺序一致才能搜索，这样很不方便，因为书签多了，不可能按顺序记住的
> 原来用 Alfred 就可以，才开始试用的 HapiGo 也可以，谷歌浏览器自带的书签搜索就更强大了
> 
> > 这里我只是举例子哈，实际情况搜索 **utools** 就出来了， 我的书签有好几千个，每个标题里我都写的关键字，有点类似火狐的 tag，我想到啥，直接输入关键字就能出来，不用保持他的顺序

你的提议很好，我之前也考虑过这个乱序关键词查询的方案。

在这里简单说说最终没有安排这个功能的原因，主要是作为utools插件的限制。

一方面utools插件有个很大的限制就是插件内不能带上二进制文件，也就是说一些可执行文件是不能放在插件里提供功能使用，而乱序查询的关键是分词和索引生成，用一些分词的手段拆分标题，让每个词都可以被用来搜索；但JavaScript是一个运行速度很慢的语言，纯JavaScript实现的分词库凤毛麟角，而且效果不好，还慢，目前能用的分词库都是二进制编译的，utools插件不能用。

另一方面是索引，其实也是性能问题，实现乱序查询的索引是非常庞大的，utools插件不是软件级别的服务，不能保证自己一直在运行，所以大多数进入插件的时候都等于全新打开。不能在内存保留索引，就会在打开的时候加载很慢，之前试过是接近1到2秒，这种打开插件的速度对于随手打开就用的插件是不可接受的。

综合考虑，最后还是没有做这个功能，之后有空再研究这个功能的话，就看utools有没有为插件提供新的能力或者用户自己另外下载工具辅助了。

utools插件和你提到的Alfred和hapigo终究还是不是一个系统级别的东西，在独立软件里很轻松就能做到的功能，在插件里就没办法了。

**Comment by jing2si** [comment]
@lanyuanxiaoyao 非常感谢你这么详细耐心的回答，理解了问题的原因。

**Comment by jing2si** [comment]
@lanyuanxiaoyao 我修复了官方的书签搜索，达到了我要的效果，https://github.com/uTools-Labs/utools-tpl-bookmarks-search/pull/3

**Comment by lanyuanxiaoyao** [comment]
> @lanyuanxiaoyao 我修复了官方的书签搜索，达到了我要的效果，[uTools-Labs/utools-tpl-bookmarks-search#3](https://github.com/uTools-Labs/utools-tpl-bookmarks-search/pull/3)

新版本已加入乱序关键字功能
