### ISSUE TITLE
wps书签乱码

### ISSUE THREAD

**Issue by kazetyan** [LanyuanXiaoyao-Studio/utools-recent-projects#3]
## 异常截图
![image](https://user-images.githubusercontent.com/50894526/192958527-61bdb1ee-906a-4189-b459-71cc00faca8b.png)
## 注解表截图
![image](https://user-images.githubusercontent.com/50894526/192958424-a5e5910b-99a6-456a-9740-c92f8084d924.png)

**Comment by lanyuanxiaoyao** [comment]
已在`3.10.3`尝试解决，如果还有问题，请重新打开此 issue 反馈
