### ISSUE TITLE
升级到最新版本变得非常卡顿，经常超时被中断

### ISSUE THREAD

**Issue by DQinYuan** [LanyuanXiaoyao-Studio/utools-recent-projects#4]
系统：linux deepin
utools 版本：3.0.3
插件版本 3.10.2(880)

![image](https://user-images.githubusercontent.com/23725000/198020362-8926a15d-5051-41ab-91bd-f7b84d024c1c.png)

![image](https://user-images.githubusercontent.com/23725000/198020851-93310d39-5e85-4df7-9e95-013a283443c6.png)

除了搜索功能外，连偏好设置都很卡顿

**Comment by lanyuanxiaoyao** [comment]
> 系统：linux deepin utools 版本：3.0.3 插件版本 3.10.2(880)
> 
> ![image](https://user-images.githubusercontent.com/23725000/198020362-8926a15d-5051-41ab-91bd-f7b84d024c1c.png)
> 
> ![image](https://user-images.githubusercontent.com/23725000/198020851-93310d39-5e85-4df7-9e95-013a283443c6.png)
> 
> 除了搜索功能外，连偏好设置都很卡顿

抱歉 Github 的提醒无法及时看到，我在下一个版本`3.10.5`尝试优化加载性能的问题，可以尝试一下，如果还有问题，请重新打开此 issue 反馈
